### PR TITLE
Grease Monkey API change (GM.xmlHttpRequest)

### PR DESCRIPTION
**Pull request by paponius**

### CODE REVIEW

**Comment by Ede123** [comment]
Is there a backwards-compatible way to implement this?

I'm still  using GreaseMonkey 3.17 and obviously wouldn't want to break my own set-up...

**Comment by paponius** [comment]
It also came across my mind later that TamperMonkey might not like this either.
I'll add a polyfill and check it in TamperMonkey. I don't have a Violentmonkey to test.

**Comment by paponius** [comment]
Added a polyfill. Header contains both GM.xmlHttpRequest and GM_xmlhttpRequest and it seems not to matter in both GreaseMonkey/Firefox and TamperMonkey/Chrome on which I was testing.

I did not test on version <4 if the actual polyfill works. But it should. Would you mind?
Should remove console.log after test.

**Comment by Ede123** [comment]
Yes, works nicely.

```
defining GM  Rotten_Tomatoes_Link_On_IMDb.user.js:57:3
defining GM.xmlHttpRequest  Rotten_Tomatoes_Link_On_IMDb.user.js:60:3
```

**Comment by paponius** [comment]
ok, I removed the console calls.
also now I found this.
https://github.com/greasemonkey/gm4-polyfill
It might be an overkill but seems promising as an easy solution. Maybe will come handy for your other scripts.

**Comment by Ede123** [comment]
Yep, seems interesting. Thanks a lot for looking into this!

**Pull request merged**
